# See: .github/workflows/labeler.yml and https://github.com/marketplace/actions/labeler
design:
  - any: ['napari_plot/resources/**/*']

documentation:
  - any: ['docs/**/*', 'docs/*']

qt:
  - any: ['napari_plot/_qt/**/*.py', 'napari_plot/qt/**/*.py']

task:
  - any: ['.github/**/*']

tests:
  - any: ['**/*/_tests/**/*.py']

vispy:
  - any: ['napari_plot/_vispy']
