# The full test suite, which will be run anytime anything is merged into master.
# See test_pull_request.yml for the tests that will be run
name: Full Test

on:
  push:
    branches:
      - main
      - "v*x"
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: comprehensive-test

jobs:
  check-manifest:
    name: Check Manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uvx check-manifest

  test_uv:
    name: Test UV (${{ matrix.backend }} ${{ matrix.python-version }} ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      UV_NO_SYNC: "1"
      UV_MANAGED_PYTHON: "1"
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        backend: [pyside6, pyqt6]
        include:
          - os: windows-latest
            python-version: "3.10"
            backend: pyside2
          - os: windows-latest
            python-version: "3.11"
            backend: pyside6
          - os: windows-latest
            python-version: "3.12"
            backend: pyqt6
          # MacOS legacy Qt
          - os: macos-13
            python-version: "3.10"
            backend: pyside2
          - os: macos-13
            python-version: "3.10"
            backend: pyqt5

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - run: uv sync --no-dev --group test --extra ${{ matrix.backend }} --extra all
      - uses: pyvista/setup-headless-display-action@v4
        with:
          qt: true

      - name: Test
        run: uv run coverage run -p -m pytest -v --color=yes

      - name: Upload coverage
        uses: actions/upload-artifact@v7
        with:
          name: covreport-${{ matrix.os }}-py${{ matrix.python-version }}-${{ matrix.backend }}
          path: ./.coverage*
          include-hidden-files: true